# Generated by Django 2.0.6 on 2018-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provide',
            field=models.CharField(choices=[('bye', 'Предоставить'), ('sell', 'Получить')], default='sell', max_length=25),
        ),
    ]
