# Generated by Django 2.0.6 on 2018-06-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180617_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
