# Generated by Django 2.0.6 on 2018-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20180618_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_coins',
            field=models.IntegerField(default=1),
        ),
    ]
