# Generated by Django 2.0.6 on 2018-06-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0005_profile_photo'),
        ('service', '0006_service_time_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='worker',
        ),
        migrations.AddField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='mauth.Profile'),
            preserve_default=False,
        ),
    ]
